### ISSUE TITLE
Wrong link in /contact page

### ISSUE THREAD

**Issue by dawranliou** [DawChihLiou/dawchihliou.github.io#49]
Hey your personal site is really good looking! 

I came across the [/contact page](https://dawchihliou.github.io/contact) and found the link:

> Just want to say hi? Ping me over on [Twitter](https://www.linkedin.com/in/dawchihliou)!

It points to your LinkedIn profile instead of Twitter.  Pretty sure this is just an small oversight.  

I really like your Transparency statement and keep up the good work!

**Comment by DawChihLiou** [comment]
Thank you so much❤️ Fix is patched.
https://github.com/DawChihLiou/dawchihliou.github.io/commit/9b7451c93968ec67e18503a5e3369dc7004c3cd9
